"""initial_schema

Revision ID: 7149f0321ee9
Revises: 
Create Date: 2026-08-21 07:31:03.350385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7149f0321ee9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('PRODUCT_USER', 'AUTHORITY', name='user_roles_enum', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('water_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_water_sources_id'), 'water_sources', ['id'], unique=False)
    op.create_index(op.f('ix_water_sources_source_code'), 'water_sources', ['source_code'], unique=True)
    op.create_table('monitoring_stations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_code', sa.String(length=100), nullable=False),
    sa.Column('water_source_id', sa.Integer(), nullable=False),
    sa.Column('station_name', sa.String(length=255), nullable=False),
    sa.Column('zone', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('public_warning', sa.String(length=100), nullable=False),
    sa.Column('public_message', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['water_source_id'], ['water_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_stations_id'), 'monitoring_stations', ['id'], unique=False)
    op.create_index(op.f('ix_monitoring_stations_station_code'), 'monitoring_stations', ['station_code'], unique=True)
    op.create_index(op.f('ix_monitoring_stations_water_source_id'), 'monitoring_stations', ['water_source_id'], unique=False)
    op.create_table('product_devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_code', sa.String(length=100), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('device_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_devices_device_id'), 'product_devices', ['device_id'], unique=True)
    op.create_index(op.f('ix_product_devices_id'), 'product_devices', ['id'], unique=False)
    op.create_index(op.f('ix_product_devices_owner_id'), 'product_devices', ['owner_id'], unique=False)
    op.create_index(op.f('ix_product_devices_product_code'), 'product_devices', ['product_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_devices_product_code'), table_name='product_devices')
    op.drop_index(op.f('ix_product_devices_owner_id'), table_name='product_devices')
    op.drop_index(op.f('ix_product_devices_id'), table_name='product_devices')
    op.drop_index(op.f('ix_product_devices_device_id'), table_name='product_devices')
    op.drop_table('product_devices')
    op.drop_index(op.f('ix_monitoring_stations_water_source_id'), table_name='monitoring_stations')
    op.drop_index(op.f('ix_monitoring_stations_station_code'), table_name='monitoring_stations')
    op.drop_index(op.f('ix_monitoring_stations_id'), table_name='monitoring_stations')
    op.drop_table('monitoring_stations')
    op.drop_index(op.f('ix_water_sources_source_code'), table_name='water_sources')
    op.drop_index(op.f('ix_water_sources_id'), table_name='water_sources')
    op.drop_table('water_sources')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
